"""Create PerformanceUser table

Revision ID: 31634f498dfe
Revises: 
Create Date: 2025-08-22 16:22:22.706216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31634f498dfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_links')
    with op.batch_alter_table('balances_bloqueados', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('amount_usdt',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('amount_crypto',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_terminado'))
        batch_op.drop_index(batch_op.f('idx_user_currency_exchange'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balances_bloqueados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_currency_exchange'), ['user_id', 'currency', 'exchange'], unique=False)
        batch_op.create_index(batch_op.f('idx_terminado'), ['finished'], unique=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('amount_crypto',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('amount_usdt',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    op.create_table('referral_links',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('referred_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
